<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreFruta extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nombre' => 'required|string|max:10',
            'precio' => 'required|numeric|min:1|max:100',
            'fecha' => 'required'
        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
